FROM alpine

ENV DOCKERIZE_VERSION v0.6.1
RUN apk add wget docker redis
RUN echo 'nameserver 8.8.8.8' > /etc/resolv.conf \
        && wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
        && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
        && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

COPY docker_configs/redis-cluster-builder.sh entrypoint.sh
