logging.level.com.talkdesk: 'trace'
http.retry.interval: 2000
http.retry.max.attempts: 3

spring:
  profiles.active: dev
  application.name: playground
  redis.cluster.nodes: redis-node1:6379,redis-node2:6379,redis-node3:6379

---
management:
  server.port: 8081

  endpoint:
    health:
      probes.enabled: true
      group:
        readiness.include: readinessState,diskSpace,redis,redisConnection
        liveness.include: livenessState,ping,redisConnection
      enabled: true
      show-details: ALWAYS
      show-components: ALWAYS
    prometheus.enabled: true

  metrics:
    # instrumentation of requests handled by Spring MVC
    web.server.request.autotime.enabled: true
    distribution.percentiles-histogram.http:
      server.requests: true
      client.requests: true

  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      path-mapping:
        prometheus: metrics
      exposure.include:
        - health
        - prometheus
